### ISSUE TITLE
Question: tree deletion order and further restore

### ISSUE THREAD

**Issue by jensens** [4teamwork/ftw.trash#6]
> Only the root node of the deleted structure can be restored and thus provides IRestorable. Restoring  children without their deleted parents cannot work since the parent is missing.

Given a structure `/a/b/c` 

Given the case that first `c` got deleted, later `a` got deleted.

Now `c` can not be restored any longer w/o `a` restored beforehand. 

Is this case supported?

**Comment by jone** [comment]
@jensens I've just released the version `ftw.trash = 1.2.0`, which includes a fix in the behavior of nested trashed folders. There was a change in the behavior compared to the initial idea.

It now works like this:
When a content is removed, it is marked as trashed and restorable, children are only marked as trashed.
Only restorable content appears in the trash.
Restoring will fail with an error when the parent of the content is also trashed. The reason is that the content is restored into its old parent (it is actually never moved), which would make sense when the parent is also trashed.

So your example works like that:
- Given `/a/b/c`
- when `c` is trashed, it appears in the trash
- when `a` is trashed, it appears in the trash too - we now see `a` and `c` in the trash
- when I try to restore `c`, it will fail with an error message that the parent is still trashed and thus `c` is not restorable
- when I restore `a`, `c` is still trashed but can now be restored

Does that answer your question?

**Comment by jensens** [comment]
Yes, thanks!
